from app.rag.embeddings.embedder import TextEmbedder

from app.db.qdrant_client import QdrantVectorDB
from app.schemas.query_schema import QueryRequest, QueryResponse

# BM25 Retrieval Service
# Vector Search Retrieval Service
# Elasticsearch Retrieval Service

class QueryService:
    def __init__(self):
        self.embedder = TextEmbedder()
        self.vector_db = QdrantVectorDB()
        self.collection_name = "ehr_documents"

    def process_query(self, request: QueryRequest) -> QueryResponse:
        try:
            # Embed the query and search for relevant documents in the vector database
            query_embedding = self.embedder.embed(request.query)
            search_results = self.vector_db.search_vectors(
                collection_name=self.collection_name,
                query_vector=query_embedding,
                top_k=5
            )

            # Extract the text of the retrieved documents
            source_docs = [result.payload.get("text", "") for result in search_results]
            
            # Return only the list of documents; the prompt formatting happens in ChatModel
            # The response field is left empty as the actual answer will be generated by the LLM
            return QueryResponse(response="", source_documents=source_docs)
        except Exception as e:
            return QueryResponse(response=f"Error processing query: {str(e)}", source_documents=None)