FROM node:20-alpine

WORKDIR /app

ARG API_BASE_URL
ARG NEXT_PUBLIC_API_BASE
ENV API_BASE_URL=${API_BASE_URL}
ENV NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}

# Install dependencies
COPY frontend/package*.json ./
RUN npm ci --legacy-peer-deps

# Copy frontend source code
COPY frontend ./

# Build the Next.js app
RUN npm run build

# Expose prod port
EXPOSE 3000

# Start production server
CMD ["npm", "start"]
