FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY frontend/package*.json ./
RUN npm ci --legacy-peer-deps

# Copy frontend source code
COPY frontend ./

# Build the Next.js app
RUN npm run build

# Expose prod port
EXPOSE 3000

# Start production server
CMD ["npm", "start"]
