from pydantic import BaseModel, Field
from typing import List, Optional

class ChatRole(str):
    USER = "user"
    ASSISTANT = "assistant" 
    SYSTEM = "system"

class ChatMessage(BaseModel):
    role: ChatRole = Field(..., description="The role of the message sender (user, assistant, or system).")
    content: str = Field(..., description="The content of the message.")

class ChatRequest(BaseModel):
    messages: List[ChatMessage] = Field(..., description="A list of chat messages forming the conversation history.")

class ChatResponse(BaseModel):
    response: str = Field(..., description="The response generated by the LLM based on the conversation history.")
    source_documents: Optional[List[str]] = Field(None, description="List of source documents used to generate the response, if applicable.")