from pydantic import BaseModel, Field
from typing import List, Optional


class RetrievedDocument(BaseModel):
    # add fields that are relevant for the retrieved documents, e.g., title, abstract, url, etc.
    article_id: str
    title: str
    url: str
    abstract: str
    score: float


class QueryRequest(BaseModel):
    query: str = Field(..., description="The natural language query to be processed.")


class QueryResponse(BaseModel):
    response: str = Field(
        ..., description="The response generated by the LLM based on the query."
    )
    source_documents: list[RetrievedDocument] = Field(
        ...,
        description="List of documents retrieved from the vector database that were used to generate the response.",
    )
