from pydantic import BaseModel, Field
from typing import List, Optional

class QueryRequest(BaseModel):
    query: str = Field(..., description="The natural language query to be processed.")

class QueryResponse(BaseModel):
    response: str = Field(..., description="The response generated by the LLM based on the query.")
    source_documents: Optional[List[str]] = Field(None, description="List of source documents used to generate the response, if applicable.")
