from pydantic import BaseModel, Field

class QueryRequest(BaseModel):
    query: str = Field(..., description="The natural language query to be processed.")
class QueryResponse(BaseModel):
    response: str = Field(..., description="The response generated by the LLM based on the query.")
    