from pydantic import BaseModel, Field
from app.schemas.source_document_schema import SourceDocument


class RetrievedDocument(BaseModel):
    # add fields that are relevant for the retrieved documents, e.g., title, abstract, url, etc.
    article_id: str
    title: str
    url: str
    abstract: str
    combined_text: str = ""
    section: str = ""
    score: float


class QueryRequest(BaseModel):
    query: str = Field(..., description="The natural language query to be processed.")


class QueryResponse(BaseModel):
    response: str = Field(
        ..., description="The response generated by the LLM based on the query."
    )
    llm_docs: list[RetrievedDocument] = Field(
        ...,
        description="List of documents retrieved from the vector database that were used to generate the response.",
    )
    source_documents: list[SourceDocument] = Field(
        ...,
        description="List of source documents (article_id, title, url, score) that were retrieved and returned in the API response.",
    )
